apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: java-app
  name: java-application
  namespace: java-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort 
  selector:
    app: states
